function getVungleReplacementTokens() {
	return {
		"00": "#01b27a",
		"01": "Download",
		"02": "6",
		"03": "subscription",
		"04": "0",
		"05": "6",
		"06": "false",
		"07": "DisneyNOW – Episodes \u0026 Live TV",
		"08": "Disney",
		"09": "icon.png",
		"0a": "4.5-stars.svg",
		"0b": "https://apps.apple.com/us/app/disneynow-episodes-live-tv/id529997671?uo=4",
		"0c": "43e52a80ec10ea9d628f12fc1ef05e46.mp4-1280x720-hevc-Q2.mp4",
		"0d": "https://privacy.vungle.com/",
		"0e": "false",
		"0f": "Vungle, Inc. understands the importance of privacy. Vungle operates a mobile ad network (the 'Ad Network' or the 'Services') through which Vungle displays targeted, contextual ads.",
		"10": "Read Vungle's Privacy Policy",
		"11": "Close",
		"12": "Close this ad?",
		"13": "Are you sure you want to skip this ad? You must finish watching to claim your reward.",
		"14": "Close",
		"15": "Continue",
		"16": "false",
		"17": "true",
		"18": "true",
		"19": "true",
		"1a": "ios",
		"1b": "15.0",
		"1c": "6.10.1",
		"1d": "off",
		"1e": "product_view",
		"1f": "overlay_view",
		"20": "product_view",
		"21": "overlay_view",
		"22": "false",
		"23": "Accept",
		"24": "Deny",
		"25": "Personalized Ads",
		"26": "Ads are personalized. Denying would disable it",
		"27": "aggressive"
	};
}
